name: Build, Pack & Publish Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'

# Required for publishing to GitHub Packages and creating releases/tags
permissions:
  contents: write
  packages: write

jobs:
  build-pack-publish:
    if: github.event.pull_request.merged == true
    uses: cpdevtools/git-flow/.github/workflows/build-pack-publish.yml@main
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit
